### ISSUE TITLE
ClassCastException after updating

### ISSUE THREAD

**Issue by minarja1** [prof18/RSS-Parser#89]
Hello, I have updated a bunch of dependencies in my project, including:

- your library (rssparser) to the MavenCentral version
- kotlin to version 1.5.10

and now I'm getting the following error whenever I try to parse any feed:

```
E/RSSSourceRepository$updateDB: java.lang.ClassCastException: kotlin.Unit cannot be cast to com.prof.rssparser.Channel
        at com.prof.rssparser.Parser$getChannel$2.invokeSuspend(Parser.kt:177)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

NOTE: This issue does not appear when I downgrade RSSParser to 3.1.2. Only in version 3.1.3 and up.

**Comment by prof18** [comment]
I should have fixed it yesterday! 😅 https://github.com/prof18/RSS-Parser/commit/68dc46a4cf8b10334ef8c7c39acddf2cd0dfc0c1

I'm gonna release a new version of the library between today and tomorrow.

**Comment by prof18** [comment]
I've just released the new version! (It could take some time before MavenCentral will show it)
